
coverage:
  range: "70...90"
  status:
    patch:
      default:
        branches:
        - master
        - dev
        target: '80'
    project:
      default:
        branches:
        - master
        - dev
